all:
  children:
    ubuntu:
      hosts:
        local-dev:
          ansible_host: 192.168.164.128
          ansible_user: ansible
          ansible_become: true
          ansible_become_method: sudo
    dev_servers:
      children:
        ubuntu:
