---
- name: Load OS-family specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Update package cache
  ansible.builtin.package:
    update_cache: "{{ update_cache }}"
  when: update_cache | bool
  retries: 3
  delay: 5

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  retries: 3
  delay: 5

- name: Configure timezone
  ansible.builtin.timezone:
    name: UTC

- name: Verify system health
  ansible.builtin.shell: |
    systemctl is-active --quiet systemd
    echo "System is healthy"
  register: health_check
  changed_when: false
  failed_when: health_check.rc != 0
