# .github/workflows/ansible-lint.yml
name: Ansible Lint
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
  push:
    branches: ["main", "stable", "release/v*"]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--verbose"
          setup_python: "true"